<?php

namespace Mix\Log;

use Mix\Core\Component\AbstractComponent;

/**
 * Class MultiHandler
 * @package Mix\Log
 * @author liu,jian <coder.keda@gmail.com>
 */
class MultiHandler extends AbstractComponent implements LoggerHandlerInterface
{

    /**
     * 初始化事件
     */
    public function onInitialize()
    {
        parent::onInitialize(); // TODO: Change the autogenerated stub
        // 类型检查
        foreach ($this as $handler) {
            if (!($handler instanceof LoggerHandlerInterface)) {
                $class = get_class($handler);
                throw new \RuntimeException("{$class} type is not 'Mix\Log\LoggerHandlerInterface'");
            }
        }
    }

    /**
     * 写入日志
     * @param $level
     * @param $message
     * @return bool
     */
    public function write($level, $message)
    {
        // TODO: Implement write() method.
        foreach ($this as $handler) {
            /** @var LoggerHandlerInterface $handler */
            $handler->write($level, $message);
        }
    }

}
